image:
  name: registry.gitlab.com/join-up/cross-cutting/tools/codefresh:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
variables:
  PLAN: plan.tfplan
  JSON_PLAN_FILE: tfplan.json
  GITLAB_TOKEN: $CI_BUILD_TOKEN


before_script:
  - codefresh auth create-context --api-key $CODEFRESH_API_TOKEN
  - helm repo add upy_public cm://h.cfcr.io/upy/public
  - helm repo add upy_default cm://h.cfcr.io/upy/default

stages:
  - publish


publish-hello:
  stage: publish
  script:
    - cd hello
    - helm package . --version $CI_COMMIT_REF_SLUG
    - helm push . upy_default --version $CI_COMMIT_REF_SLUG
  only:
    refs:
      - tags

publish-services-dependency:
  stage: publish
  script:
    - cd services-dependency
    - helm package . --version $CI_COMMIT_REF_SLUG
    - helm push . upy_default --version $CI_COMMIT_REF_SLUG
  only:
    refs:
      - tags

publish-spring:
  stage: publish
  script:
    - cd spring-boot
    - helm package . --version $CI_COMMIT_REF_SLUG
    - helm push . upy_default --version $CI_COMMIT_REF_SLUG
  only:
    refs:
      - tags

publish-dns:
  stage: publish
  script:
    - cd dns
    - helm package . --version $CI_COMMIT_REF_SLUG
    - helm push . upy_default --version $CI_COMMIT_REF_SLUG
  only:
    refs:
      - tags
