apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bun-hono.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bun-hono.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bun-hono.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        forcedRef: {{ .Values.image.ref }}
        app.kubernetes.io/name: {{ include "bun-hono.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: {{ .Values.restartPolicy }}
      containers:
        - name: {{ .Values.appName }}
          image: "{{ include "bun-hono.image" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.container}}
          {{- if or .environment .secrets }}
          env:
            {{- range $key, $value := .environment }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- if .secrets }}
            {{- range .secrets }}
            {{- $secretName := .name }}
            {{- range $key, $value := .env }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: {{ $value }}
            {{- end }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.http.containerPort }}
              protocol: TCP
          {{- if .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.container }}
          {{- if .configMaps }}
          volumeMounts:
            {{- range .configMaps }}
            {{- if .mountPath }}
            - name: {{ .name }}-volume
              mountPath: {{ .mountPath }}
              {{- if .subPath }}
              subPath: {{ .subPath }}
              {{- end }}
              readOnly: {{ .readOnly | default true }}
            {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
      {{- with .Values.container }}
      {{- if .configMaps }}
      volumes:
        {{- range .configMaps }}
        {{- if .mountPath }}
        - name: {{ .name }}-volume
          configMap:
            name: {{ .name }}
            {{- if .items }}
            items:
              {{- toYaml .items | nindent 14 }}
            {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}