{{- $httpUrl := include "dns.http-full-url" . -}}
{{- $httpSecret := include "dns.http-ssl-secret" . -}}
{{- $httpService := include "dns.http-seviceName" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: kong
  name: {{ $httpService }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    konghq.com/strip-path: {{.Values.stripPath}}
    #    konghq.com/plugins: httpbin-auth
    {{- if .Values.httpsOnly }}
    konghq.com/override: https-only
    {{- end }}
    kubernetes.io/tls-acme: "true"
    {{- if .Values.methods }}
    konghq.com/methods: {{ .Values.methods }}
    {{- end}}
    cert-manager.io/cluster-issuer: letsencrypt-cluster-prod
    kubernetes.io/ingress.class: kong
    {{- if .Values.externalDnsEnabled }}
    external-dns.alpha.kubernetes.io/hostname: {{ $httpUrl }}
  {{- end }}
spec:
  tls:
    - secretName: {{ $httpSecret }}
      hosts:
        - {{ $httpUrl }}
  rules:
    - host: {{ $httpUrl}}
      http:
        paths:
          - backend:
              serviceName: {{ $httpService }}
              servicePort: {{ .Values.port  }}
