apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns.fullname" . }}
  namespace: kong
spec:
  type: ExternalName
  externalName: {{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local
  ports:
    - port: 80
      name: low
      protocol: TCP
      targetPort: 8080
