{{- $httpService := include "dns.http-seviceName" . -}}
apiVersion: v1
kind: Service
metadata:
    name: {{ $httpService }}
    namespace: kong
spec:
    type: ExternalName
    externalName: {{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local
    ports:
        - port: {{ .Values.port  }}
          name: http
          protocol: TCP
          targetPort: {{ .Values.targetPort  }}

