{{- if .Values.internalConfig }}
apiVersion: v1
data:
  application-kube.yml: |-
    grpc:
      port: {{.Values.grpc.port}}
      enable-reflection: {{.Values.grpc.enableReflection}}
    spring:
      application:
        name: {{.Values.appName}}
      config:
        use-legacy-processing: false
      zipkin:
        enabled: ${monitoring.zipkin.enabled:true}
        baseUrl: ${monitoring.zipkin.url:}
    {{- if .Values.enableDefaultConfig}}
      data:
        mongodb:
          uri: mongodb+srv://${mongo.user}:${mongo.password}@${mongo.cluster.address}
          database: {{ .Values.appName }}
      kafka:
        producer:
          batch-size: 8000
        properties:
          bootstrap.servers: ${kafka.bootstrap.servers}
          sasl.mechanism: PLAIN
          sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule   required username='${kafka.user}'   password='${kafka.password}';"
          security.protocol: SASL_SSL
          basic.auth.credentials.source: USER_INFO
          schema.registry.basic.auth.user.info: ${kafka.user.info}
          schema.registry.url: ${kafka.registry.url}
    {{- end }}
    graphql:
      packages:
        - "io.joinupy"
    logging:
      level:
        root: {{.Values.loglLevel.root}}
    {{- if .Values.loglLevel.packages}}
{{  toYaml .Values.loglLevel.packages | indent 8 }}
    {{- end}}
kind: ConfigMap
metadata:
  labels:
    name: {{ .Values.appName }}-config-prop
  name: {{ .Values.appName }}-config-prop
  namespace: {{ .Values.namespace }}
{{- end }}
