apiVersion: v1
data:
  application-kube.yml: |-
    grpc:
      port: {{.Values.grpc.port}}
      enable-reflection: {{.Values.grpc.enableReflection}}
    spring:
      profiles:
      application:
        name: {{.Values.appName}}
        active: kube
        include: default
      config:
        use-legacy-processing: true
    {{- if .Values.enableDefaultConfig}}
      data:
        mongodb:
          uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER_ADDRESS}
          database: {{ .Values.appName }}
      kafka:
        properties:
          bootstrap.servers: ${KAFKA_BOOTSTRAP_SERVERS}
          sasl.mechanism: PLAIN
          sasl.jaas.config: "org.apache.kafka.common.security.plain.PlainLoginModule   required username='${KAFKA_USER}'   password='${KAFKA_PASSWORD}';"
          security.protocol: SASL_SSL
          basic.auth.credentials.source: USER_INFO
          schema.registry.basic.auth.user.info: ${KAFKA_USER_INFO}
          schema.registry.url: ${KAFKA_REGISTRY_URL}
    {{- end }}
    graphql:
      packages:
        - "io.joinupy"
    logging:
      level:
        root: {{.Values.loglLevel.root}}
    {{- if .Values.loglLevel.packages}}
{{  toYaml .Values.loglLevel.packages | indent 8 }}
    {{- end}}
kind: ConfigMap
metadata:
  labels:
    name: {{ .Values.appName }}-config-prop
  name: {{ .Values.appName }}-config-prop
  namespace: {{ .Values.namespace }}
