apiVersion: v1
data:
  application-kube.yml: |-
    spring:
      profiles:
        active: kube
        include: default
      data:
        mongodb:
          uri: mongodb+srv://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_CLUSTER_ADDRESS}
          database: {{ .Values.appName }}
    graphql:
      packages:
        - "io.joinupy"
    logging:
      level:
        root: INFO
kind: ConfigMap
metadata:
  labels:
    name: {{ .Values.appName }}-config-prop
  name: {{ .Values.appName }}-config-prop
  namespace: {{ .Values.namespace }}
