apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "spring-boot.fullname" . }}
  labels:
{{ include "spring-boot.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 6565
      name: grpc
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/name: {{ include "spring-boot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

