apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "spring-boot.fullname" . }}
  labels:
{{ include "spring-boot.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.grpc.port }}
      name: grpc
      protocol: TCP
      targetPort: grpc
    {{- if .Values.rsocket.port }}
    - port: {{ .Values.rsocket.port }}
      name: rsocket
      protocol: TCP
      targetPort: rsocket
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "spring-boot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

