apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ include "spring-boot.fullname" . }}
  labels:
{{ include "spring-boot.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 6565
      name: grpc
      protocol: TCP
      targetPort: 6565
  selector:
    app.kubernetes.io/name: {{ include "spring-boot.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- $fullName := include "spring-boot.fullname" . -}}
{{- $enabledGrpc := .Values.ingress.enabledGrpc -}}
{{- $enabledHttp := .Values.ingress.enabledHttp -}}
{{- if or $enabledGrpc $enabledHttp -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  namespace: kong
  {{- if $enabledGrpc}}
  annotations:
    konghq.com/protocol: grpcs
  {{- end }}
spec:
  type: ExternalName
  externalName: {{ .Values.appName }}.{{ .Values.namespace }}.svc.cluster.local
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 6565
      name: grpc
      protocol: TCP
      targetPort: 6565
{{- end}}
